nelmio_api_doc:
  areas:
    default:
      path_patterns:
        - ^/api(?!/doc$)
  documentation:
    openapi: 3.0.0
    info:
      title: "API Empresas-Socios"
      description: "API para gerenciamento de empresas e sócios"
      version: "1.0.0"
    components:
      schemas:
        Empresa:
          type: object
          properties:
            id:
              type: integer
              example: 1
            nome:
              type: string
              example: "Empresa Exemplo"
        Socio:
          type: object
          properties:
            id:
              type: integer
              example: 1
            nome:
              type: string
              example: "Sócio Exemplo"
            empresa:
              $ref: "#/components/schemas/Empresa"